workflows:
  unity-ios:
    name: Unity iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Install Unity version
        script: |
          # Instalar Unity 2021.3.45f1 desde Unity Hub
          wget https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage -O UnityHub.AppImage
          chmod +x UnityHub.AppImage
          ./UnityHub.AppImage -- --headless install --version 2021.3.45f1
      - name: Build Unity project
        script: |
          # Construir proyecto usando la versión de Unity instalada
          /Applications/Unity/Hub/Editor/2021.3.45f1/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -projectPath $CM_BUILD_DIR \
            -executeMethod BuildScript.BuildiOS \
            -quit
      - name: Install CocoaPods
        script: |
          cd build/ios
          pod install
      - name: Build and Sign iOS app
        script: |
          xcodebuild -workspace build/ios/Unity-iPhone.xcworkspace \
                     -scheme Unity-iPhone \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/build/ios/Unity.xcarchive archive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/ios/Unity.xcarchive \
                     -exportPath $CM_BUILD_DIR/build/ios \
                     -exportOptionsPlist build/ios/exportOptions.plist
    artifacts:
      - build/ios/*.ipa

