workflows:
  unity-ios:
    name: Unity iOS Build
    environment:
      unity:
        version:2021.3.29f1 
      xcode: latest
    scripts:
      - name: Build Unity project
        script: |
          # Construir el proyecto usando Unity instalado en el entorno de Codemagic
          /Applications/Unity/Hub/Editor/2021.3.29f1/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -projectPath $CM_BUILD_DIR \
            -executeMethod BuildScript.BuildiOS \
            -quit
      - name: Install CocoaPods
        script: |
          # Instalar dependencias de iOS con CocoaPods
          cd build/ios
          pod install
      - name: Build and Sign iOS app
        script: |
          # Construir y firmar la aplicación iOS con Xcode
          xcodebuild -workspace build/ios/Unity-iPhone.xcworkspace \
                     -scheme Unity-iPhone \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/build/ios/Unity.xcarchive archive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/ios/Unity.xcarchive \
                     -exportPath $CM_BUILD_DIR/build/ios \
                     -exportOptionsPlist build/ios/exportOptions.plist
    artifacts:
      - build/ios/*.ipa

